version: '3.8'
# services / containers
services:
    # express app
    api_mawaddah:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_mawaddah
        image: api_mawaddah:0.0.2
        restart: always
        ports:
            - 5021:5000
        environment:
            PORT: 5000
            JWTSECRET: MAWADDAHINDONESIA2024
            # for prisma
            DATABASE_URL: mysql://root:my-secret-pw@mawaddah_mysql:3306/mawaddah_indonesia
        volumes:
            - mawaddah_api_public:/app/public
        networks:
            - mawaddah_api_network
        depends_on:
            - mawaddah_mysql

    # mysql database
    mawaddah_mysql:
        container_name: mawaddah_mysql
        image: mysql:8.3.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: mawaddah_indonesia
        volumes:
            - mawaddah_mysql:/var/lib/mysql
        networks:
            - mawaddah_api_network

# volumes
volumes:
    mawaddah_api_public:
        name: mawaddah_api_public
    mawaddah_mysql:
        name: mawaddah_mysql

# networks
networks:
    mawaddah_api_network:
        name: mawaddah_api_network
        driver: bridge
