# services / containers
services:
    # express app
    api_mawaddah:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_mawaddah
        image: api_mawaddah:0.0.19
        restart: always
        ports:
            - 5021:5000
            - 5555:5555
        environment:
            PORT: 5000
            JWTSECRET: MAWADDAHINDONESIA2024
            JWT_EXPIRATION: 180
            # for prisma
            DATABASE_URL: postgresql://postgres:postgres@mawaddah_postgre:5432/mydb?schema=mawaddah_dev
            # DATABASE_URL: mysql://root:my-secret-pw@mawaddah_mysql:3306/mawaddah_indonesia
            # gmail for blast email. use different docker compose file to extend
            GMAIL_APP_PASSWORD: abc abc abc
            GMAIL_ADDRESS: test@gmail.com
            # credential for midtrans payment gateway. use different docker compose file to extend
            MIDTRANS_CLIENT_KEY: SB-Mid-client-aaaaa
            MIDTRANS_SERVER_KEY: SB-Mid-server-bbbb
        volumes:
            - mawaddah_api_public:/app/public
        networks:
            - mawaddah_api_network
        depends_on:
            - mawaddah_postgre
            # - mawaddah_mysql

    # postgre database
    mawaddah_postgre:
        container_name: mawaddah_postgre
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - mawaddah_postgre:/var/lib/postgresql/data
        networks:
            - mawaddah_api_network
    # mysql database
    # mawaddah_mysql:
    #     container_name: mawaddah_mysql
    #     image: mysql:8.3.0
    #     command: --default-authentication-plugin=mysql_native_password
    #     restart: always
    #     environment:
    #         MYSQL_ROOT_PASSWORD: my-secret-pw
    #         MYSQL_DATABASE: mawaddah_indonesia
    #     volumes:
    #         - mawaddah_mysql:/var/lib/mysql
    #     networks:
    #         - mawaddah_api_network

# volumes
volumes:
    mawaddah_api_public:
        name: mawaddah_api_public
    mawaddah_postgre:
        name: mawaddah_postgre
    # mawaddah_mysql:
    #     name: mawaddah_mysql

# networks
networks:
    mawaddah_api_network:
        name: mawaddah_api_network
        driver: bridge
