openapi: "3.0.2"
info:
    title: Client API
    version: "1.0"
    contact:
        name: "Rizjami Putera"
        email: "rizjamiputera@gmail.com"
        url: "https://udaputera.com"
servers:
  - description: Client API
    url: "{url}:5000/v1"
    variables:
        url:
            default: "http://localhost:5000"
paths:
    "/client":
        get:
            tags:
            - Client
            description: Get Client Detail
            responses:
                200:
                    description: "OK"
                    content:
                        application/json:
                            examples:
                                dummy:
                                    $ref: "#/components/examples/dummy"
                                data:
                                    $ref: "#/components/examples/client"
        patch:
            tags:
            - Client
            description: Update client, semua parameter optional, minimal ada 1 paramater
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                about:
                                    type: string
                                phone:
                                    type: string
                                    format: phone
                                address:
                                    type: string
                                taaruf_muqoddimah:
                                    type: string
                                login_muqoddimah:
                                    type: string
                                signup_muqoddimah:
                                    type: string
                                youtube:
                                    type: string
                                facebook:
                                    type: string
                                twitter:
                                    type: string
                                instagram:
                                    type: string
                                linkedin:
                                    type: string
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            examples:
                                data:
                                    $ref: "#/components/examples/client"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
                404:
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
components:
    examples:
        dummy:
            summary: dummy
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                name: "-"
                about: null
                phone: "-"
                address: true
                taaruf_muqoddimah: null
                login_muqoddimah: null
                signup_muqoddimah: null
                youtube: null
                facebook: null
                twitter: null
                instagram: null
                tiktok: null
                linkedin: null
        client:
            summary: client
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                name: "Mawaddah Indonesia"
                about: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro sint recusandae dicta voluptatum quo incidunt obcaecati amet architecto optio facere!"
                phone: "021-999-999"
                address: "Jl Kemenyan 1, Jagakarsa, DKI Jakarta, Indonesia, 12630"
                taaruf_muqoddimah: "Assaalaamualaikum Warohmatullah Wabarokatuh"
                login_muqoddimah: "Assaalaamualaikum Warohmatullah Wabarokatuh"
                signup_muqoddimah: "Assaalaamualaikum Warohmatullah Wabarokatuh"
                youtube: "https://youtube.com"
                facebook: "https://facebook.com"
                twitter: "https://twitter.com"
                instagram: "https://instagram.com"
                tiktok: "https://tiktok.com"
                linkedin: "https://linkedin.com"