openapi: "3.0.2"
info:
    title: Biodata API
    version: "1.0"
    contact:
        name: "Rizjami Putera"
        email: "rizjamiputera@gmail.com"
        url: "https://udaputera.com"
servers:
  - description: Bioadata API
    url: "{url}:5000/v1"
    variables:
        url:
            default: "http://localhost:5000"
paths:
    "/biodata":
        post:
            tags:
            - Biodata
            description: Create biodata, hanya auth user yg bisa melakukan.
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                biodata:
                                    type: string
                                phone:
                                    type: string
                                    format: phone
                                manhaj:
                                    type: string
                                    format: enum (Salaf | Baru Belajar | Non Salaf)
                                gender:
                                    type: string
                                    format: enum (Perempuan | Laki-Laki)
                                status:
                                    type: string
                                    format: enum (Lajang | Menikah | Duda | Janda)
                                married_permission:
                                    type: string
                                    format: enum (Poligami | Non-Poligami)
                                dob:
                                    type: string
                                    format: date
                                birth_place:
                                    type: string
                                birth_order:
                                    type: number
                                domicile_town:
                                    type: string
                                domicile_province:
                                    type: string
                                hometown_province:
                                    type: string
                                ethnic:
                                    type: string
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            examples:
                                sliders:
                                    $ref: "#/components/examples/biodata"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
        get:
            tags:
            - Biodata
            description: Get biodata by auth user
            responses:
                200:
                    description: "OK"
                    content:
                        application/json:
                            examples:
                                sliders:
                                    $ref: "#/components/examples/biodata"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
        patch:
            tags:
            - Biodata
            description: Create biodata, hanya auth user yg bisa melakukan.
            requestBody:
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                biodata:
                                    type: string
                                phone:
                                    type: string
                                    format: phone
                                manhaj:
                                    type: string
                                    format: enum (Salaf | Baru Belajar | Non Salaf)
                                gender:
                                    type: string
                                    format: enum (Perempuan | Laki-Laki)
                                status:
                                    type: string
                                    format: enum (Lajang | Menikah | Duda | Janda)
                                married_permission:
                                    type: string
                                    format: enum (Poligami | Non-Poligami)
                                dob:
                                    type: string
                                    format: date
                                birth_place:
                                    type: string
                                birth_order:
                                    type: number
                                domicile_town:
                                    type: string
                                domicile_province:
                                    type: string
                                hometown_province:
                                    type: string
                                ethnic:
                                    type: string
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            examples:
                                sliders:
                                    $ref: "#/components/examples/biodata"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
components:
    examples:
        biodata:
            summary: Biodata
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                userId: "768c6b44-2334-4fa0-95a5-1dffgs617a033"
                biodata: "Aku seorang kapiten"
                phone: "+62 8888-888-8888"
                manhaj: "Salaf"
                gender: "Laki-laki"
                status: "Lajang"
                married_permission: "Poligami"
                dob: "1990-01-01"
                birth_place: "Jakarta"
                birth_order: "2"
                domicile_town: "Jakarta"
                domicile_province: "DKI Jakarta"
                hometown_province: "Sumatera Selatan"
                ethnic: "Chaniago"
